version: '2.2'
services:
  stagingdb:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DATABASE=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # user: 1000:1000
    ports:
      - "5432:5432"
    networks:
      - esgstagingnetwork

  stagingadminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    networks:
      - esgstagingnetwork

networks:
  esgstagingnetwork:
    driver: bridge

